# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a420e39f5ec1b50ac6ab4bc1a4c1c4db2e0cbd9560b0d70c3fb940e6c2812abc881c72cffb6ae89049389f59d1805563c8ca75a919ef24b8211394b69fb5a39

test:
  secret_key_base: ce32ceff0e0288bc981eb80fb173f59e9974a56f8f86359bb16ac2b1a9e44c67fcec955f9cd25b41299a1252f1ad3615229a56eba3671a32cae8cef1ec970309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
